### ISSUE TITLE
How to see ENTIRE inventory?

### ISSUE THREAD

**Issue by peralmered** [Dhebug/Encounter#2]
It's pretty easy to pick up so many things that the rows on the screen can't show all items. Is there a way to get a complete list of all items you're carrying?

**Comment by Dhebug** [comment]
You can't at the moment, the original game was restricting you to 8 items max.
So the two possibilities I see are either:
- Restrict you back to 8 items.
- Make it possible to scroll up and down the view of items with the arrows
other ideas?

**Comment by peralmered** [comment]
The "classic" way is the command INVENTORY, which would list everything. I find myself typing it all the time, despite knowing it's not in the vocabulary of the game :-)

**Comment by peralmered** [comment]
Test comment, to make sure notifications work!

**Comment by Dhebug** [comment]
Fixed in version 0.8.4. The inventory is now restricted to 8 items, if you try to get more you get a message telling you to drop one before.
