### ISSUE TITLE
Spelling error for combined "sulphur & saltpetER"

### ISSUE THREAD

**Issue by peralmered** [Dhebug/Encounter#3]
When you combine "sulphur" and "saltpetre", the result is "sulphur & saltpetER"

**Comment by Dhebug** [comment]
Yeah I keep getting tricked by that word, the US and British wordings are different, and both are written a tiny bit different from the French version!

**Comment by peralmered** [comment]
Silly anecdote: My father was technical writer for SonyEricsson, and they had their VERY OWN specific english, which was a MIX of UK and US english, and he said it was very confusing at first. So SonyEricsson actually kept their own little dictionary of what spelling was in THEIR english. Fucking nightmare, but I can see their reasoning.

Feel free to delete this entry, just had to share :-)

**Comment by Dhebug** [comment]
Fixed in version 0.8.1, please reopen if not working as expected.
