### ISSUE TITLE
Achievements aren't saved

### ISSUE THREAD

**Issue by peralmered** [Dhebug/Encounter#4]
...but scores are, so the game IS writing back to disk!

**Comment by Dhebug** [comment]
Going to investigate that this evening, that's most probably something completely dumb.
The achievements are stored in the same slot on disk as the high scores and the "how many times was the game launched", so if the scores are saved and if the loading messages change each time you launch the game, it means the slot is properly saved... just that it does not have the updated achievements.

**Comment by Dhebug** [comment]
Found the problem: When adding the code to count the number of launches, I properly loaded the save file, but in the process I ended up clearing the achievement list... oops

**Comment by Dhebug** [comment]
Fixed in version 0.8.1, please reopen if not working as expected.
